steps:
    # Step 1: Pull the base image
    - name: 'gcr.io/cloud-builders/docker'
      args: ['pull', 'python:3.5']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/cloud-builders/docker', '.']
options:
    logging: CLOUD_LOGGING_ONLY