steps:
  # Step 1: Build your Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/sniim-scraper-430915/sniim-scraper-image', '.']

  # Step 2: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/sniim-scraper-430915/sniim-scraper-image']

  # Step 3: Update Kubernetes deployment with the new image
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'sniim-scraper-deploy'  # Replace with your deployment name
      - 'sniim-scraper-container=gcr.io/sniim-scraper-430915/sniim-scraper-image:latest'  # Replace with your Docker image reference
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-west1'  # Replace with your GKE cluster's zone
      - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1'  # Replace with your GKE cluster's name
      - 'CLOUDSDK_CONTAINER_USE_V1_API_CLIENT=false'  # Optional: Use if you encounter API version issues

options:
  logging: CLOUD_LOGGING_ONLY
